# Part 1: Level 1 - Fundamentals (Questions 1–25)

**1. What is a Workflow in AEM?**
**Answer:** A workflow is a sequence of steps used to automate a business process. It allows AEM to move a "payload" (usually a page or asset) through a series of predefined tasks (e.g., Review $\rightarrow$ Approval $\rightarrow$ Activation).

**2. What is the "Payload" in a workflow?**
**Answer:** The payload is the object that the workflow is operating on. It is usually a path to a node in the JCR (e.g., `/content/dam/my-image.jpg`). The payload is passed from one step to the next.

**3. What is a Workflow Model?**
**Answer:** A Workflow Model is the "blueprint" or the visual design of the process. It defines the steps, the order of execution, and the logic (splits/joins). It is stored under `/var/workflow/models`.

**4. What is a Workflow Instance?**
**Answer:** An instance is a specific "run" of a workflow model. While the model is the blueprint, the instance is the actual execution for a specific piece of content.

**5. What is a Participant Step?**
**Answer:** A step that requires human intervention. The workflow pauses at this step and assigns a task to a specific user or group. The workflow only proceeds once the user completes the task.

**6. What is a Process Step?**
**Answer:** An automated step that executes Java code (a `WorkflowProcess`). No human intervention is required. Examples include sending an email, renaming a file, or activating a page.

**7. What is a Workflow Launcher?**
**Answer:** A launcher is a trigger that automatically starts a workflow based on specific events, such as:
*   Node created.
*   Node modified.
*   Specific property changed.
*   Path match.

**8. What is the difference between a "Step" and a "Process"?**
**Answer:** A **Step** is the structural element in the Workflow Model (the box). A **Process** is the actual logic (the Java class) assigned to a Process Step.

**9. How do you assign a user to a Participant Step?**
**Answer:** You can assign them statically (specific user/group) or dynamically (using a "Dynamic Participant Step" which uses a Java class to determine the user at runtime).

**10. What is the purpose of the Workflow Console (`/libs/cq/workflow/content/console.html`)?**
**Answer:** It allows administrators to monitor running instances, see who is assigned to which task, cancel stuck workflows, and view the workflow history.

**11. What are "Workflow Metadata"?**
**Answer:** Metadata are key-value pairs attached to a workflow instance. They are used to pass data between steps that isn't part of the payload (e.g., storing the name of the person who approved the content).

**12. What is an OR-Split?**
**Answer:** A decision point where the workflow can take one of several paths based on a condition. Only one path is chosen.

**13. What is an AND-Join?**
**Answer:** A synchronization point. The workflow waits until **all** parallel paths leading into the join are completed before proceeding to the next step.

**14. What is an AND-Split?**
**Answer:** A point where the workflow splits into multiple parallel paths. All paths are executed simultaneously.

**15. What is the difference between "Complete" and "Terminate" in a workflow?**
**Answer:** "Complete" marks the current step as finished and moves to the next. "Terminate" stops the entire workflow instance immediately.

**16. Can a workflow be started manually?**
**Answer:** Yes, via the "Workflows" menu in the AEM Sites/Assets console or via the Workflow Console.

**17. What is the "Workflow Session"?**
**Answer:** The `WorkflowSession` is the API used to interact with the workflow engine, start instances, and manage tasks.

**18. How does a workflow handle a payload that is deleted while the workflow is running?**
**Answer:** Usually, the next step will fail with a "Payload not found" error and the workflow instance will be marked as failed.

**19. What is a "Dynamic Participant Step"?**
**Answer:** A step where the assigned user is not hardcoded but is determined by a Java class implementing `DynamicParticipantStep`. This is useful for "Assign to the author of the page."

**10. What is the "Workflow Engine"?**
**Answer:** The underlying OSGi service that manages the execution of models, tracks instances, and handles the queuing of tasks.

**21. What is a "User Task"?**
**Answer:** Any task generated by a Participant Step that appears in the AEM Inbox of the assigned user.

**22. What is the "Inbox" in AEM?**
**Answer:** The UI component where users see all the workflow tasks assigned to them.

**23. Can a workflow model be edited while instances are running?**
**Answer:** Yes, but changes typically apply to **new** instances. Running instances usually follow the version of the model they started with.

**24. What is the "Payload Type"?**
**Answer:** A way to filter which workflows can be run on which content (e.g., only run the "Asset Workflow" on `dam:Asset` types).

**25. What is the purpose of the "Workflow Model Versioning"?**
**Answer:** It allows developers to keep a history of the model and roll back to a previous version if a new process logic is buggy.

---

# Part 2: Level 2 - Implementation & Custom Development (Questions 26–50)
*Focus: Coding custom steps, Java APIs, and developer-level logic.*

**26. Which Java interface must you implement to create a custom Workflow Process?**
**Answer:** `com.adobe.granite.workflow.WorkflowProcess`.

**27. Explain the `execute` method in the `WorkflowProcess` interface.**
**Answer:** This is the core method. It takes a `WorkItem` and a `WorkflowSession`.
*   `WorkItem`: Provides access to the current step's context.
*   `WorkflowSession`: Used to interact with the JCR and workflow engine.

**28. How do you retrieve the payload path inside a custom `WorkflowProcess`?**
**Answer:** 
`String payloadPath = workItem.getWorkflowData().getPayload().toString();`

**29. How do you get the `ResourceResolver` inside a custom workflow step?**
**Answer:** You should use a **Service User**. Inject `ResourceResolverFactory` and use `getServiceResourceResolver(authInfo)`. Never use the session provided by the workflow if it doesn't have the required permissions.

**30. How do you add metadata to a workflow instance programmatically?**
**Answer:** 
`workflowData.setWorkflowData("myKey", "myValue");`
This allows subsequent steps to read this value.

**31. How do you read metadata in a subsequent step?**
**Answer:** 
`String value = workItem.getWorkflowData().getWorkflowData("myKey");`

**32. How do you programmatically start a workflow from a Java class?**
**Answer:**
1. Get the `WorkflowSession` from the `WorkflowService`.
2. Create a `WorkflowData` object with the payload path.
3. Call `session.startWorkflow(model, workflowData)`.

**33. What is the difference between `WorkflowSession` and `ResourceResolver`?**
**Answer:** `WorkflowSession` is for managing the workflow state (starting/stopping/tracking), whereas `ResourceResolver` is for manipulating the actual content in the JCR.

**34. How do you make a workflow step "conditional" (skip a step based on logic)?**
**Answer:** You can implement a custom `WorkflowProcess` that checks a condition. If the condition isn't met, the process can either do nothing or use the `WorkflowSession` to move the instance to a different step.

**35. How do you implement a "Dynamic Participant Step"?**
**Answer:** Implement the `DynamicParticipantStep` interface. The `getParticipants` method should return a list of user/group paths (e.g., `/home/users/admin`) based on the payload.

**36. What is the role of the `WorkItem` object?**
**Answer:** The `WorkItem` represents the current execution of a specific step. It contains the `WorkflowData` and the current status of the step.

**37. How do you handle errors in a custom workflow process?**
**Answer:** Wrap the logic in a `try-catch` block. If a critical error occurs, you can throw a `WorkflowException` to mark the step as failed.

**38. How do you send an email from a workflow step?**
**Answer:** Use the AEM `MessageGatewayService` or an external Java Mail API. You retrieve the recipient's email from the payload or metadata and send the message.

**39. How do you activate a page programmatically within a workflow?**
**Answer:** Use the `Replicator` API. Inject the `Replicator` service and call `replicate(session, payloadPath)`.

**40. What is the "Workflow Launcher" configuration?**
**Answer:** It is an OSGi configuration. You define the `event` (e.g., `NODE_CREATED`), the `node path`, and the `workflow model` to trigger.

**41. How do you ensure a Workflow Launcher only triggers for specific properties?**
**Answer:** In the Launcher configuration, you can specify a "Condition" (Property name and value) that must be met for the workflow to start.

**42. What is the "Workflow Process" OSGi registration?**
**Answer:** Your custom `WorkflowProcess` class must be annotated with `@Component(service = WorkflowProcess.class)`. This allows the Workflow Model UI to see it in the dropdown list.

**43. How do you handle "looping" in a workflow (going back to a previous step)?**
**Answer:** This is usually done via a "Decision" step (OR-split). If the reviewer rejects the content, the path leads back to the "Authoring" step.

**44. What is a "Workflow Listener"?**
**Answer:** A listener is a service that monitors workflow events (e.g., when a workflow starts, completes, or fails) and executes logic in response.

**45. How do you stop a workflow instance programmatically?**
**Answer:** Use `WorkflowSession.removeWorkflow(workflowInstanceId)`.

**46. How do you change the payload of a workflow while it is running?**
**Answer:** You can update the `WorkflowData` object using `workflowData.setPayload(newPath)`.

**47. What is the importance of the `Sling Resource Resolver` in workflows?**
**Answer:** Since workflows often run in the background (system context), the Resource Resolver ensures that the code has the correct permissions to modify content without needing a logged-in user`.

**48. How do you pass complex objects between workflow steps?**
**Answer:** Since metadata only supports Strings, you should serialize the object to JSON and store it as a String in the workflow metadata, then deserialize it in the next step`.

**49. How do you implement a "Wait" or "Delay" in a workflow?**
**Answer:** You can create a custom `WorkflowProcess` that uses a timer or, more commonly, use a Participant step that stays open until a certain time/event occurs`.

**50. What is the `WorkflowModel` API?**
**Answer:** It is the Java API used to programmatically create or modify workflow models (though this is rarely done; models are usually created in the UI)`.

